server:
  port: ${PORT:8080}
spring:
  application:
    name: craft
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres.gyeufqcpsqjisywqrezm
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    com.mcm.craft: DEBUG